languageCode = "en"
languageName = "English"
weight = 1
title = "Cloudian"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Connie"
  headline = "A place to document what I learned and what I think"
  bio = "Optimistic yet lazy (working on that)"
   links = [
     { github = "https://github.com/conni3" },
   ]