# -- Theme Options --
colorScheme             = "marvel"
defaultAppearance       = "dark"
autoSwitchAppearance    = true

# Global defaults
defaultBackgroundImage  = "cover.png"

enableSearch            = true
enableCodeCopy          = true

[params]
  mainSections         = ["posts"]
  math = true


[header]
  layout              = "basic"

[footer]
  showCopyright       = true
  showThemeAttribution= true
  showAppearanceSwitcher = true
  showScrollToTop     = true

[homepage]
  layout              = "background"
  homepageImage       = "cover.png"
  showRecent          = true
  showRecentItems     = 9
  showMoreLink        = true
  showMoreLinkDest    = "/posts"
  cardView            = true
  cardViewScreenWidth = false
  layoutBackgroundBlur= true

[article]
  showHero            = true
  heroStyle           = "background"
  showDate            = false
  showDateUpdated     = false
  showAuthor          = true
  showBreadcrumbs     = true
  showDraftLabel      = true
  showPagination      = true
  invertPagination    = false
  showReadingTime     = true
  showTableOfContents = true
  showTaxonomies      = true
  showWordCount       = true
  showSummary         = true

[list]
  showHero                 = true
  heroStyle                = "background"
  layoutBackgroundBlur     = true
  layoutBackgroundHeaderSpace = true  
  showBreadcrumbs          = true
  showSummary              = true
  showTableOfContents      = true
  showCards                = true
  groupByYear              = false
  cardView                 = true
  cardViewScreenWidth      = false

